language: node_js
node_js:
  - "8"
cache: npm
script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - npm
  - echo 'Testing!'
  - npm test:prod
install:
  - npm install -g firebase-tools
after_success:
  - npm build
  - firebase deploy --token "$FIREBASE_TOKEN"